### ISSUE TITLE
It is a great work! How to train - Rotate3D  dataset??

### ISSUE THREAD

**Issue by c1a1o1** [ali-design/gan_steerability#1]
It is a great work! How to train - Rotate3D  dataset??

**Comment by ali-design** [comment]
Thanks! You need to use your dataset as the target instead of *target_fn* in the code. Currently, we approximate a 3D target by projecting a 2D image on a billboard and rotating it (for more background, please see homography: https://en.wikipedia.org/wiki/Homography_(computer_vision)).

**Comment by c1a1o1** [comment]
Thank  you  very much!
