### ISSUE TITLE
will you provide a pytorch version?

### ISSUE THREAD

**Issue by kkiritoo** [ali-design/gan_steerability#3]

**Comment by chail** [comment]
Hi! I've made a pytorch version in a colab notebook for tutorial purposes here: https://colab.research.google.com/drive/1WRcCnYX_fjN3hp5-DXhGquXHs44hgVV6
Feel free to check it out, it should help you get started.

**Comment by kkiritoo** [comment]
> Hi! I've made a pytorch version in a colab notebook for tutorial purposes here: https://colab.research.google.com/drive/1WRcCnYX_fjN3hp5-DXhGquXHs44hgVV6
> Feel free to check it out, it should help you get started.

Thanks very much!

**Comment by kkiritoo** [comment]
> Hi! I've made a pytorch version in a colab notebook for tutorial purposes here: https://colab.research.google.com/drive/1WRcCnYX_fjN3hp5-DXhGquXHs44hgVV6
> Feel free to check it out, it should help you get started.
Sorry, I cannot run it well.┭┮﹏┭┮ could you share your biggan model?
ls: cannot access '/content/gdrive/My Drive/gan_steerability_tutorial/weights_model/100k/': No such file or directory

**Comment by kkiritoo** [comment]
> Hi! I've made a pytorch version in a colab notebook for tutorial purposes here: https://colab.research.google.com/drive/1WRcCnYX_fjN3hp5-DXhGquXHs44hgVV6
> Feel free to check it out, it should help you get started.

OH! i found the weights file in biggan-pytorch :)

**Comment by ali-design** [comment]
Thank you for your interest. Yes, the pytorch version will be provided soon. Hopefully this colab notebook would be a good starting point in the meantime.
