### ISSUE TITLE
How do we train and test on our custom dataset?

### ISSUE THREAD

**Issue by ashisht96** [ali-design/gan_steerability#4]

**Comment by ali-design** [comment]
Could you please be more specific? In general, you would need to first train a gan, e.g., stylegan, on your dataset. (Please refer the description of any model you would want to train in its website.) Having this pertained model, you can load it to our framework. Then you would need to train the walk(s). For defining any custom transformation, you would need to modify the get_target_fn() to get your desired target images in np format (not tensor) and so you can feed them to the network.
