### ISSUE TITLE
The related code about reducing transformation limits

### ISSUE THREAD

**Issue by berylsheep-up** [ali-design/gan_steerability#5]
Hello, this is an good job! 
I found the paper conclude some research about jointly optimizing the generator and the walk parameters with data augmentation ( argmin G, W). I am working on this topic, will you have plan to open source code? Thanks!

**Comment by ali-design** [comment]
Thank you for your interest. Yes, we will add that.

**Comment by ali-design** [comment]
Please see the code in the directory steer_aug/DCGAN-tensorflow
